#!/bin/zsh

# Python
alias ploneenv='source ~/venv/plone/bin/activate'
alias aenv='source bin/activate'
alias plist='pip list --format=columns'

# Plone
alias pinf='bin/instance fg'
alias pin='bin/instance'
alias pbo='bin/buildout'
alias pbn='bin/buildout -N'
alias fakemail='sudo python /Users/bernd/.zsh/scripts/fakemail.py --path "/Users/bernd/Development/fakemail/" --background --open --port 25 --log "/Users/bernd/Development/fakemail/fakemail.log"'
alias cleanup-versions='python /Users/bernd/.zsh/scripts/cleanup_versions.py'

# Basic Builtin
alias ls='ls -hC'
alias la='ls -lAp'
alias lt='ls -lAtp'
alias ll='la'
alias rmf='rm -rf'
alias rsynca='rsync -rtvpl'

# Applications
alias preview='/Applications/Preview.app/Contents/MacOS/Preview'
alias c='charm'

# GIT
alias gcu='echo -n `git remote show origin | grep "Fetch URL" | cut -d " " -f 5`|pbcopy'
alias gca='git commit -S --all --amend --no-edit'
alias grc='git rebase --continue'
alias grm='git rebase -S -i master'
alias glog='git log --graph'
alias gpf='git push --force --signed="if-asked"'
alias gcp='git cherry-pick -S'
alias gc='git commit -S -m'
alias gco='git checkout'
alias gri='git rebase -S -i'
alias gra='git rebase --abort'
alias gst='git status'
alias gp='git push --signed="if-asked"'
alias gsa='git stash'
alias gsp='git stash pop'
alias gpl='git pull'
alias gfa='git fetch --all'

# Misc
alias fsize='du -sh'

#Extensions
alias -s pdf=preview
alias -s odt=preview
alias -s doc=preview
alias -s docx=preview
alias -s rtf=preview
alias -s ods=preview
alias -s xls=preview
alias -s xlsx=preview
alias -s odp=preview
alias -s ppt=preview
alias -s pptx=preview

alias -s htm=chrome
alias -s html=chrome
alias -s xml=chrome

alias -s png=preview
alias -s jpg=preview
alias -s gif=preview

alias -s php=php
alias -s py=python

alias -s zcml=sublime
alias -s txt=sublime
alias -s rst=sublime
alias -s md=sublime
alias -s ini=sublime
alias -s cfg=sublime
