#!/bin/zsh

# Reload configuration
alias reload='source ~/.zshrc'

# Python Virtualenvs
alias ploneenv='source ~/venv/plone/bin/activate'
alias aenv='source bin/activate'

# Plone buildout and instance
alias pinf='bin/instance fg'
alias pin='bin/instance'
alias pbo='bin/buildout'

# Basic Builtin
alias la='ls -l -A'
alias ls='ls -Gh'
alias ll='ls -l'
alias grep='grep --color'
alias rmf='rm -rf'
alias rsynca='rsync -rtvpl'
# Search in files in current path
function greps() {
    if [ -n "$1" ] # or better, if [ -n "$1" ]
    then
	grep -rn -A3 -B3 $2 -e $1
    else
        grep -rn -A3 -B3 . -e $1
    fi
}


# Applications
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias Preview='/Applications/Preview.app/Contents/MacOS/Preview'

# GIT
alias gcu='echo -n `git remote show origin | grep "Fetch URL" | cut -d " " -f 5`|pbcopy'
alias gca='git commit --all --amend --no-edit'
alias grc='git rebase --continue'
alias grm='git rebase -i master'
alias glog='git log --graph'
alias gpf='git push --force'
alias gcp='git cherry-pick'
alias gc='git commit -m'
alias gco='git checkout'
alias gri='git rebase -i'
alias gst='git status'
alias gp='git push'

# Automatically add "/.." if you type more the two dots. This means it goes
# from this ".." to this "../..". Like this you can fast change to a parent directory.

rationalise-dot() {
if [[ $LBUFFER = *.. ]]; then
    LBUFFER+=/..
else
    LBUFFER+=.
fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

# Misc
alias fsize='du -sh'

#Extensions
alias -s pdf=preview
alias -s odt=preview
alias -s doc=preview
alias -s docx=preview
alias -s rtf=preview
alias -s ods=preview
alias -s xls=preview
alias -s xlsx=preview
alias -s odp=preview
alias -s ppt=preview
alias -s pptx=preview

alias -s htm=chrome
alias -s html=chrome
alias -s xml=chrome

alias -s png=preview
alias -s jpg=preview
alias -s gif=preview

alias -s php=php
alias -s py=python
